### ISSUE TITLE
如果条目的布局都有差异,是否需要嵌套多个NestFullListView

### ISSUE THREAD

**Issue by MrShuHong** [mcxtzhang/NestFullListView#1]
你好,我目前还在使用Inflater.inflate 这种方式,写起来很恶心. 如果每个条目的布局有很大差异, 是否Scrollview里面嵌套多个NestFullListView才能实现呢

**Comment by mcxtzhang** [comment]
是的，我自己的项目里就是如此， 是ScrollView下面 同层级嵌套了多个NestFullListView。
这种类似多种itemType的场景概念，暂时我还没有去试着实现，因为那样的话，复用起来的难度就比较高了，

**Comment by MrShuHong** [comment]
我也是这样,  真的好恶心

**Comment by MrShuHong** [comment]
,updateUI里面的逻辑似乎只针对条目的增减来进行更新,如果bean里面的属性变化了,好像update就没有效果了

**Comment by mcxtzhang** [comment]
bean里的数据变了，update也会有效果的，只要数据刷新(updateUI),onBind()方法会重走一次的
