### ISSUE TITLE
感谢投稿到 Gank。

### ISSUE THREAD

**Issue by daimajia** [mcxtzhang/NestFullListView#3]
通读了所有的方案，感觉可操作性都不够强，另外重用能力也很弱。

最好的方案还是你最后提及的 RecyclerView 方案，数据结构不好组织是真的，不过建议试试  Drakeet 开源的 MultiType，可能会有新的启发。

https://github.com/drakeet/MultiType

**Comment by mcxtzhang** [comment]
是的呢，这种方案在我心中不是很好的，所以是发出来求拍砖的，希望找到最优雅之道，稍后我看看这个项目找找灵感。
 不过我好像没有投稿到gank哈~我只分享到了掘金和自己的CSDN，没敢出去献丑，我还是有自知之明的，啊哈，可能是别的网友投稿的，因为这篇文章大大出乎我意料的在掘金有380+的收藏， 说实话，我其他的几篇文章自我感觉比这篇好很多，收藏也才100 200+，搞不懂大众的口味了，
啊哈，不过以后如果有我觉得自己满意的作品出来，我会投的，感谢你的回复哈，我会继续努力，
上代码家是我的目标之一XD。

**Comment by daimajia** [comment]
其他平台的读者都是看个标题，然后收藏，很少考究内容的。

Gank 这边儿每个稿子我都会通读一遍，保证发出去的裤子都是最佳实践。

欢迎继续投稿过来哇。

另外... 上代码家？

![image](https://cloud.githubusercontent.com/assets/2503423/18863186/a71e446c-84c2-11e6-9e2e-9ca8eb66ccc7.png)
