### ISSUE TITLE
刷新数据源应该怎么使用啊

### ISSUE THREAD

**Issue by ghost** [mcxtzhang/NestFullListView#5]

**Comment by mcxtzhang** [comment]
可查看博文 http://blog.csdn.net/zxt0601/article/details/52494665  或者下载Demo， 里面都提到  利用 nestFullIstView.updateUI();方法刷新

**Comment by ghost** [comment]
谢谢，我再看一看，如果列表有查看更多和收起，实现思路应该是怎样的呢？

**Comment by mcxtzhang** [comment]
在上次更新我已经支持了footerView，利用footerview的显示和隐藏即可
我自己项目里是这么使用的：
                    if (overSize) {
                        if (nestFullListView.getFooterCount() == 0) {
                            View footer = mInflater.inflate(R.layout.ayc_footer_job_list_more, nestFullListView, false);
                            footer.setOnClickListener(new View.OnClickListener() {
                                @Override
                                public void onClick(View v) {
                                    nestFullListView.removeFooterView(0);
                                    nestFullListView.updateUI();
                                }
                            });
                            nestFullListView.addFooterView(footer);
                        }
                    } else {
                        nestFullListView.removeFooterView(0);
                    }
