### ISSUE TITLE
是否可以根据position 增加或者删除item

### ISSUE THREAD

**Issue by wei3** [mcxtzhang/NestFullListView#6]
项目里遇到多个动态的item，问题里面包括多个exitText（三个以上），试过listview 与 recycleview，遇到getview复用的问题，每次输入其中一个exittext ,listview就会整个item（position）遍历一下，结果所有的exitext的结果都一样了，很是苦恼，试过通用hashmap 根据postion 保存值，但是delete 就郁闷了，------------这个问题一直从上线苦恼我到现在，最后是自定义extends LinearLayout 实现类似listivew的原理，看到楼主的文章，不理解怎么根据position 增加或者删除item ，还有给item增加动画，能否给些意见，万分感谢

**Comment by mcxtzhang** [comment]
根据position 增加、删除Item的话，ListView也没提供这个功能吧？  不过本例用的是LL模拟的Lv，你真的想根据position修改Item也是可以的，利用nestFullListView.getChildAt(postion) ,拿到ItemView 进行修改、删除吧。记得要同步更新数据集。 如果不做定向修改，直接修改数据集，然后调用updateUI方法也可以。

给ITem增加动画的话，你搜一下如何给LinearLayout增加动画，它本身是支持布局动画的，不过我没有使用过。

**Comment by wei3** [comment]
谢谢
