### ISSUE TITLE
加一个点击跳转！

### ISSUE THREAD

**Issue by Xiaocai9527** [mcxtzhang/NestFullListView#7]
holder.getView(R.id.layout5).setOnClickListener(new View
                                                .OnClickListener() {
                                            @Override
                                            public void onClick(View v) {
                                                Intent intent = new Intent();
                                                intent.setClass(MyWebActivity.this, MyWebActivity
                                                        .class);
                                                intent.putExtra("id", recomends.get(pos).getId());//pos是onbind回调参数
                                                intent.putExtra("url", recomends.get(pos).getUrl());
                                                intent.putExtra("to", "zaker");
                                                startActivity(intent);
                                            }
                                        });
楼猪，用到了你的这个。但是可惜并没有用到update，因为我的数据是固定几个，方便了我不用重复写5个RelativeLayout。看了这个我也不想在双层滑动里再嵌套listview了！

**Comment by mcxtzhang** [comment]
是的，就算不用update，也可以减少很多重复的代码量。
话说你这个issue是要问什么问题嘛 ，看你写的点击跳转没啥毛病啊

**Comment by Xiaocai9527** [comment]
。。。没问题啊，想说你搞得好

**Comment by mcxtzhang** [comment]
哈哈 ，我以为你提什么问题给我呢，吓得我虎躯一震
